### PR TITLE
Report outputs

### PR DESCRIPTION
**Pull request by esteinig**
*  `--stats/-s` now outputs the summary to `stdout` --> #31

```bash
nanoq -i test.fq -s > report.txt
```

*  `--report/-r` always writes the report to a file

```bash
nanoq -i test.fq -s -r report.txt
```

* report is **not** output to `stderr` when filtering (or ever); use explicit report file option

```bash
nanoq -i test.fq -r report.txt > reads.fq
```

* `--json/-j` outputs the report in JSON (equivalent to `-vvv`) --> #30

### CODE REVIEW

**Comment by esteinig** [comment]
@mbhall88 @kaiseriskera

How is this looking?

**Review by mbhall88 — APPROVED** [review]
LGTM

**Comment by esteinig** [comment]
* fixed JSON string output

**Comment by esteinig** [comment]
* removed `stderr` report output entirely (see first comment, edited)

**Pull request merged**
